Revert "ci: bump outdated v4 action, which would fail"
This reverts commit d819bee4311d3532db7415be725d6cbe687de5c7.

I bumped the wrong action, because I misinterpreted the following error
message:

> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/